branches:
  only:
    - travis

language: node_js
node_js: '16'

before_install:
  - npm i -g yarn
  - npm i -g lerna
  - npm i -g multi-semantic-release@2 @qiwi/semantic-release-gh-pages-plugin@5 @semantic-release/changelog@6 @semantic-release/commit-analyzer@9 @semantic-release/git@10 @semantic-release/github@8 @semantic-release/npm@8 @semantic-release/release-notes-generator@10

install:
  - yarn
  - yarn bootstrap
  - yarn build

script:
  - yarn test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - multi-semantic-release --deps.release=minor --deps.bump=inherit
