# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]
jobs:
  init:
    name: init
    runs-on: ubuntu-20.04
    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
      skip-not: ${{ steps.ci-skip-step.outputs.ci-skip-not }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: ci-skip-step
        uses: mstachniuk/ci-skip@v1

  build:
    name: build
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install deps
        run: |
          yarn --ignore-engines
          yarn bootstrap
      - run: yarn build

      - name: Save target (artifact)
        uses: actions/upload-artifact@v2
        with:
          name: target
          retention-days: 1
          # If a wildcard pattern is used, the path hierarchy will be preserved after the first wildcard pattern.
          # https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions
          path: |
            !packages/*/node_modules
            !packages/*/src
            packages
            lerna.json

  test_push:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Restore target
        uses: actions/download-artifact@v2
        with:
          name: target
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install deps
        run: |
          yarn --ignore-engines
          yarn bootstrap

      - name: Unit test only
        run: yarn test:unit

      - name: Push coverage
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: target
          retention-days: 1
          path: coverage

  test_pr:
    if: github.event_name == 'pull_request'
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        node-version: [ 14, 16 ]
    name: Test (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Restore target
        uses: actions/download-artifact@v2
        with:
          name: target
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: |
          yarn --ignore-engines
          yarn bootstrap
      - name: Unit test only
        if: matrix.node-version != '16' || matrix.os != 'ubuntu-20.04'
        run: yarn test:unit
      - name: Full test
        if: matrix.node-version == '16' && matrix.os == 'ubuntu-20.04'
        run: yarn test

  release:
    name: Release
    # https://github.community/t/trigger-job-on-tag-push-only/18076
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test_push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          depth: 0
          persist-credentials: false

      - name: Restore target
        uses: actions/download-artifact@v2
        with:
          name: target
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install deps
        run: |
          npm i -g multi-semantic-release@2 @qiwi/semantic-release-gh-pages-plugin@5 @semantic-release/changelog@6 @semantic-release/commit-analyzer@9 @semantic-release/git@10 @semantic-release/github@8 @semantic-release/npm@8 @semantic-release/release-notes-generator@10
          yarn --ignore-engines
          yarn bootstrap

      - name: Multi-semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: 'qiwibot'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: 'opensource@qiwi.com'
          GIT_COMMITTER_EMAIL: 'opensource@qiwi.com'
          GIT_AUTHOR_NAME: '@qiwibot'
          GIT_COMMITTER_NAME: '@qiwibot'
        run: multi-semantic-release
